import React, { useState, useEffect, useRef } from 'react';
// Import the Twilio Video SDK for WebRTC communication
import Video from 'twilio-video'; 

const VideoConsent = () => {
  // --- States for Smart Availability Simulator (Demo Panel) ---
  const [doctorOnline, setDoctorOnline] = useState(true); 
  const [availabilityChecked, setAvailabilityChecked] = useState(false);
  const [isDoctorAvailable, setIsDoctorAvailable] = useState(false);
  const [checking, setChecking] = useState(false);

  // --- States for Consent, Live Call, and Post-Call ---
  const [isConsentGranted, setIsConsentGranted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isCallActive, setIsCallActive] = useState(false);
  const [showPrescription, setShowPrescription] = useState(false); 
  
  const localVideoRef = useRef(null); 
  const localTracksRef = useRef([]); 

  // Step 1: Simulate checking doctor availability from backend
  const checkAvailability = () => {
    setChecking(true);
    setTimeout(() => {
      setIsDoctorAvailable(doctorOnline);
      setAvailabilityChecked(true);
      setChecking(false);
    }, 1000);
  };

  // Step 2: Handle the patient's consent submission
  const handleConsentAccept = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:5000/api/appointments/123/consent', {
        method: 'POST',
      });
      
      if (response.ok) {
        setIsConsentGranted(true);
        setIsCallActive(true);
      }
    } catch (error) {
      console.error("Error recording consent:", error);
      alert("Unable to connect to the backend. Please ensure the Node.js server is running.");
    } finally {
      setLoading(false);
    }
  };

  // Step 3: Request Twilio access token and initialize Audio/Video tracks
  useEffect(() => {
    if (isConsentGranted && isCallActive) {
      fetch('http://localhost:5000/api/video/token')
        .then(res => res.json())
        .then(data => {
          if(data.token) {
            Video.createLocalTracks({
              audio: true,
              video: { width: 640 }
            }).then(tracks => {
              localTracksRef.current = tracks;
              
              tracks.forEach(track => {
                if (track.kind === 'video' && localVideoRef.current) {
                  localVideoRef.current.appendChild(track.attach());
                }
                if (track.kind === 'audio') {
                  document.body.appendChild(track.attach());
                }
              });
            });
          } else {
            console.error("Token retrieval failed. Please verify Twilio environment variables.");
          }
        })
        .catch(err => console.error("Media streaming error:", err));
    }
  }, [isConsentGranted, isCallActive]); 

  // Step 4: Safely terminate the consultation
  const handleEndCall = () => {
    localTracksRef.current.forEach(track => {
      track.stop();
      const attachedElements = track.detach();
      attachedElements.forEach(element => element.remove());
    });
    
    setIsCallActive(false);
    setShowPrescription(true); 
  };

  // --- NEW FEATURE: Generate and Download E-Prescription File ---
  const downloadPrescription = () => {
    // 1. Create the content of the prescription
    const prescriptionText = `
=========================================
      RURAL TELEMEDICINE PLATFORM
=========================================
Consulting Doctor: Dr. Nitin
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

PATIENT PRESCRIPTION & ADVICE:
-----------------------------------------
1. Paracetamol 500mg - Take 1 tablet twice a day after meals.
2. Ensure adequate rest and stay hydrated.
3. Schedule a follow-up consultation in 3 days if symptoms persist.

* This is a digitally verified e-prescription generated by the platform. *
=========================================
    `;

    // 2. Create a Blob (a file-like object) from the text
    const blob = new Blob([prescriptionText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    // 3. Create a hidden link, click it to trigger download, and remove it
    const link = document.createElement('a');
    link.href = url;
    link.download = 'E-Prescription_Dr_Nitin.txt';
    document.body.appendChild(link);
    link.click();
    
    // 4. Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // --- Render 1: Post-Call E-Prescription Screen ---
  if (showPrescription) {
    return (
      <div style={{ textAlign: 'center', padding: '50px', fontFamily: 'sans-serif' }}>
        <h2 style={{ color: '#2e7d32' }}>✅ Consultation Completed</h2>
        <p>Thank you for using the Rural Telemedicine Platform.</p>
        
        <div style={{ border: '2px dashed #2196F3', padding: '30px', maxWidth: '400px', margin: '30px auto', borderRadius: '10px', background: '#e3f2fd' }}>
          <h3>📄 E-Prescription Ready</h3>
          <p style={{ fontSize: '14px', color: '#555' }}>Dr. Nitin has securely uploaded your medical prescription.</p>
          
          {/* Download button now triggers the real download function */}
          <button 
            onClick={downloadPrescription}
            style={{ background: '#1976D2', color: 'white', padding: '12px 24px', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', marginTop: '10px' }}
          >
            ⬇️ Download Prescription
          </button>
          
          <br />
          <button 
            onClick={() => {
              setShowPrescription(false);
              setIsConsentGranted(false);
              setAvailabilityChecked(false);
            }}
            style={{ marginTop: '20px', padding: '8px 16px', cursor: 'pointer', background: 'white', border: '1px solid #ccc', borderRadius: '4px' }}
          >
            Return to Home
          </button>
        </div>
      </div>
    );
  }

  // --- Render 2: The Active Video & Audio Room ---
  if (isConsentGranted && isCallActive) {
    return (
      <div style={{ textAlign: 'center', padding: '30px', fontFamily: 'sans-serif' }}>
        <h2>🎥 Live Consultation Room</h2>
        <p style={{ color: '#2e7d32', fontWeight: 'bold' }}>Microphone and Camera Active</p>
        
        <div 
          ref={localVideoRef} 
          style={{ width: '600px', height: '400px', background: '#222', margin: '0 auto', borderRadius: '10px', overflow: 'hidden', border: '3px solid #4CAF50', boxShadow: '0 10px 20px rgba(0,0,0,0.2)' }}
        >
        </div>

        <div style={{ marginTop: '30px' }}>
          <button 
            onClick={handleEndCall}
            style={{ background: '#f44336', color: 'white', padding: '12px 30px', border: 'none', borderRadius: '30px', cursor: 'pointer', fontWeight: 'bold', fontSize: '16px', boxShadow: '0 4px 6px rgba(0,0,0,0.2)' }}
          >
            ❌ End Consultation
          </button>
        </div>
      </div>
    );
  }

  // --- Render 3: The Pre-Call Gateway (Demo Panel + Availability + Consent) ---
  return (
    <div style={{ padding: '20px', maxWidth: '700px', margin: '0 auto', fontFamily: 'sans-serif' }}>
      
      <div style={{ padding: '15px', background: '#e3f2fd', borderRadius: '8px', marginBottom: '20px', border: '1px solid #2196F3' }}>
        <h4 style={{ margin: '0 0 10px 0', color: '#1565C0' }}>🛠️ Demo Control Panel (Doctor Status)</h4>
        <label style={{ cursor: 'pointer', fontWeight: 'bold' }}>
          <input 
            type="checkbox" 
            checked={doctorOnline} 
            onChange={(e) => {
              setDoctorOnline(e.target.checked);
              setAvailabilityChecked(false); 
            }} 
            style={{ marginRight: '10px' }}
          />
          {doctorOnline ? "🟢 Dr. Nitin is ONLINE" : "🔴 Dr. Nitin is OFFLINE"}
        </label>
        <p style={{ margin: '5px 0 0 0', fontSize: '13px', color: '#555' }}>
          Toggle this during the video presentation to demonstrate edge-case handling.
        </p>
      </div>

      <h2>Patient Waiting Room</h2>
      <div style={{ border: '1px solid #ccc', padding: '20px', borderRadius: '8px', background: '#f9f9f9', boxShadow: '0 4px 8px rgba(0,0,0,0.1)' }}>
        
        {!availabilityChecked ? (
          <div style={{ textAlign: 'center', padding: '20px 0' }}>
            <h3>Step 1: Verify Doctor Availability</h3>
            <p>Please check if Dr. Nitin is available before proceeding.</p>
            <button 
              onClick={checkAvailability}
              disabled={checking}
              style={{ background: '#2196F3', color: 'white', padding: '10px 20px', border: 'none', borderRadius: '5px', cursor: 'pointer', fontSize: '16px', fontWeight: 'bold' }}
            >
              {checking ? "Checking Server Status..." : "Check Availability"}
            </button>
          </div>
        ) : (
          <div>
            {!isDoctorAvailable ? (
              <div style={{ textAlign: 'center', color: '#d32f2f', padding: '20px', background: '#ffebee', borderRadius: '5px', border: '1px solid #ef9a9a' }}>
                <h3>❌ Doctor Unavailable</h3>
                <p>Dr. Nitin is currently offline or attending to another patient. Please try again later.</p>
                <button 
                  onClick={() => setAvailabilityChecked(false)}
                  style={{ marginTop: '10px', padding: '8px 16px', cursor: 'pointer', background: 'white', border: '1px solid #ccc', borderRadius: '4px' }}
                >
                  Go Back
                </button>
              </div>
            ) : (
              <div>
                <div style={{ background: '#e8f5e9', color: '#2e7d32', padding: '10px', borderRadius: '5px', marginBottom: '15px', textAlign: 'center', fontWeight: 'bold', border: '1px solid #a5d6a7' }}>
                  ✅ Dr. Nitin is ready for your consultation.
                </div>
                
                <h3>Step 2: Patient Consent Required</h3>
                <p>Please review the terms to start the audio/video consultation:</p>
                <ul>
                  <li>End-to-end encrypted video and audio connection.</li>
                  <li>Access to your camera and microphone is required.</li>
                  <li>A digital record of your consent will be stored securely.</li>
                </ul>
                <p>Do you agree to proceed?</p>
                
                <button 
                  onClick={handleConsentAccept} 
                  disabled={loading}
                  style={{ background: '#4CAF50', color: 'white', padding: '12px 24px', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', width: '100%' }}
                >
                  {loading ? "Recording Authorization..." : "I Agree - Join Call"}
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default VideoConsent;